# Generated by Django 3.1.7 on 2021-03-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('birth_year', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('imagen', models.CharField(blank=True, max_length=100)),
                ('url', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('episode_id', models.IntegerField()),
                ('resume', models.TextField(blank=True)),
                ('director', models.CharField(blank=True, max_length=200)),
                ('producer', models.CharField(blank=True, max_length=200)),
                ('release_date', models.DateField()),
                ('url', models.CharField(blank=True, max_length=100)),
                ('characters', models.ManyToManyField(blank=True, related_name='Characters', to='api_movies.Character')),
            ],
        ),
    ]
