# Generated by Django 3.1.7 on 2021-03-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imagen',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
